### ISSUE TITLE
fab ap.write bombs

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#137]
This is after running `fab ap.init` and `fab ap.update`.

```
$ fab ap.write
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/deads/Projects/elections14/fabfile/ap.py", line 191, in write
    _write()
  File "/Users/deads/Projects/elections14/fabfile/ap.py", line 149, in _write
    state_candidate = race['candidates'][0]['candidateID']
IndexError: list index out of range
```

**Comment by TylerFisher** [comment]
Appears that AP is returning some races without any candidates. Fun.

**Comment by onyxfish** [comment]
Was related to API funkiness on Wednesday.
