### ISSUE TITLE
fab data.update is a little broken

### ISSUE THREAD

**Issue by eads** [nprapps/elections14#492]
It needs a path.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
TypeError: load_updates() takes exactly 1 argument (0 given)
(elections14)DEads-MacBook-Pro:elections14 deads$ fab data.update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/deads/Projects/elections14/fabfile/data.py", line 30, in update
    load_updates()
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 109, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
TypeError: load_updates() takes exactly 1 argument (0 given)
```

**Comment by onyxfish** [comment]
Is this fixed?
